name: Publish to PyPI

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # Triggers when a version tag is pushed
  release:
    types: [published]  # Triggers when a GitHub release is published
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.8"
        enable-cache: true
    
    - name: Set up Python
      run: uv python install 3.11
    
    - name: Build package
      run: |
        uv build
    
    - name: Check distribution
      run: |
        uv run --with twine twine check dist/*
    
    - name: Publish to PyPI
      if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) || github.event_name == 'release'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        uv run --with twine twine upload dist/*
    
    - name: Verify installation
      if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) || github.event_name == 'release'
      run: |
        sleep 60  # Give PyPI time to update
        uv venv verify-env
        uv pip install --python verify-env task-management-mcp --no-cache-dir
        # Test the installed command
        uv run --python verify-env python -c "from task_management_mcp import TaskManagementMCP, models; print('✅ Package imports work')"
        # Test the CLI
        uv run --python verify-env task-mcp --help