name: Publish to PyPI

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.8"
        enable-cache: true
    
    - name: Set up Python
      run: uv python install 3.11
    
    - name: Install dependencies
      run: |
        uv pip install --system build twine
    
    - name: Build package
      run: |
        uv build
    
    - name: Check distribution
      run: |
        twine check dist/*
    
    - name: Publish to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*
    
    - name: Verify installation
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      run: |
        sleep 60  # Give PyPI time to update
        uv pip install --system task-management-mcp --no-cache-dir
        # Test the installed command
        python -c "import server; import models; print('✅ Package imports work')"